version: '2.1'
services:
  nodeapp2:
    ports:
      - 8084:8084
    expose:
      - 8084
    image: rsheremet/blockchain_node:latest
    command: npm run start:prod
    volumes:
      - appdata2:/var/www/node
    environment:
      - EXPRESS_PORT=8084
      - EXPRESS_HOST=192.168.46.10
      - JWT_SECRET=SuperSecretTokenyHmc7Za5xz7DnJDVdd69PHjgqbdV8LZh
      - MONGODB_URL=mongodb://nodeapp2-mongo:27017/blockchain
      - NATS_HOST=nodeapp2-nats
      - NATS_MAIN_HOST=nats-main
      - LOG_LEVEL=info
      - WALLET_API_ADDRESS=http://192.168.1.206:8081
      - MINER_ADDRESS=51b97a804ab15c135843d23c091bfccf23461afee457472996dfffbf2f3fce99
    links:
    - nodeapp2-mongo
    - nodeapp2-nats
    depends_on:
    - nodeapp2-mongo
    - nodeapp2-nats
    external_links:
    - nats-main
  nodeapp2-mongo:
    image: mongo:3.6-jessie
    volumes:
    - mongodb2:/data/db2
    ports:
    - 27217:27017
  nodeapp2-nats:
    image: rsheremet/nats:latest
    environment:
    - NATS_CLUSTER_ROUTES=nats-route://ruser:T0pS3cr3t@nats-main:6222
    ports:
    - 24222:4222
    - 26222:6222
    - 28222:8222
    external_links:
    - nats-main
volumes:
  appdata2:
    name: appdata2
    driver: local-persist
    driver_opts:
      mountpoint: /data/docker/data/blockchain_node2
  mongodb2:
    name: mongodb2
    driver: local-persist
    driver_opts:
      mountpoint: /data/docker/data/blockchain_node_mongodb2