express:
    port: EXPRESS_PORT
    debug: EXPRESS_DEBUG
    host: EXPRESS_HOST

auth:
    jwt_secret: JWT_SECRET

mongo:
    urlClient: MONGODB_URL
    urlDocker: MONGODB_URL_DOCKER

minerAddress: MINER_ADDRESS

walletAPI:
  address: WALLET_API_ADDRESS

NATS:
  currentHost: NATS_HOST
  mainHost: NATS_MAIN_HOST
  managementPort: NATS_MGM_PORT
  clientPort: NATS_CLIENT_PORT


# none/debug/info
loglevel: LOG_LEVEL